### ISSUE TITLE
SPI connection F9R ESP

### ISSUE THREAD

**Issue by NicoZobernig** [sparkfun/SparkFun_u-blox_GNSS_v3#20]
Hello, 

We are trying to get the GPS Dead Reckoning ZED-F9R breakout board to connect via SPI with an ESP32 Wrover module but are not having any success, we receive the error that the GNSS module cannot be detected. It works well using I2C. 
We have shorted the SPI connector pads on the back of the module and have ensured that everything is hooked up correctly. We have also switched to SFE_UBLOX_GNSS_SPI.

We have tried the standard example and have also tried modifying the code like this:

    SPI.begin(SCK, MISO, MOSI, SS);
    SPI.setFrequency(myClockSpeed);
    ESP_LOGI("SPI", "Trying SPI");
    while (moto_gps.begin(SPI, SS, 4000000) == false) {
        ESP_LOGI("SPI", "u-blox GNSS not detected. Retrying...");
        delay(1000);
    }

Has anyone had any success running the SPI example with an esp32 and the zed-f9r?
Any help would be greatly appreciated.

Thanks!
Nico

**Comment by shecker** [comment]
Hi Paul (@PaulZC)

Thank you for the quick reply! 
We are able to connect via SPI by resetting the board via u-blox however the connection is very unstable in the sense that it takes around 20 tries until it can establish a connection with the module and sometimes fails completely.
Is that normal behavior?

Thanks,
Simon

**Comment by PaulZC** [comment]
Hi Simon,

No, that's not normal...

I wonder if the POCI (MISO) pin needs a pull-up? Try adding a 10K pull-up resistor between POCI (MISO) and 3.3V. Does that make any difference?

If not, try analyzing the SPI traffic using a logic analyzer. Any clues there?

Best wishes,
Paul

**Comment by PaulZC** [comment]
Also check you have opened the I2C pull-up resistor jumpers.

**Comment by PaulZC** [comment]
Yes, that should be fine. The jumpers were normally-closed on the earliest boards, but we later switched to normally-open.

Hope all is well in Switzerland,
Best,
Paul

**Comment by shecker** [comment]
Hi Paul, I added a 100K pull-down to POCI (MISO), that seems to have done the trick, thanks!
Yes all is well in Switzerland, we had some busy integration weeks but things are coming together.
Hope all is well with you as well! 
Best,
Simon

**Comment by PaulZC** [comment]
Hi Simon,

All is well here. Busy as usual!

OK - glad that's working for you. But that is a surprise... I thought a pull-up might help. A pull-down _shouldn't_ make any difference. But, if it is working, it is working!

Please check your GND connection. You need to have GND, 3V3 (or 5V), PICO, POCI, SCK and CS connected between the two boards.

Please close this issue if you are happy.

Best,
Paul

**Comment by ntmmfts** [comment]
Thanks for this - resetting to default also worked for me, glad I checked the Issues!  Suggest getting the reset recommendation into the documentation.
