### ISSUE TITLE
lastCorrectionAge in UBX-NAV-PVT is missing

### ISSUE THREAD

**Issue by forstner-m** [sparkfun/SparkFun_u-blox_GNSS_v3#33]
Hello,

the bits from lastCorrectionAge in the flags3 from the UBX-NAV-PVT is missing.

At the moment the union is this:

`  union
  {
    uint8_t all;
    struct
    {
      uint8_t invalidLlh : 1; // 1 = Invalid lon, lat, height and hMSL
    } bits;
  } flags3;
`

Please change it to:

`  union
  {
    uint8_t all;
    struct
    {
      uinit8_t invalidLlh : 1; // 1 = Invalid lon, lat, height and hMSL
      uinit8_t lastCorrectionAge : 4
    } bits;
  } flags3;
`
Thank you!

Best regards,
Michael

**Comment by PaulZC** [comment]
Hi Michael,

I've added this in v3.0.16. It will be released in about 1 hour.

Best wishes,
Paul
