### ISSUE TITLE
Compatibility with MIA-M10

### ISSUE THREAD

**Issue by simon88** [sparkfun/SparkFun_u-blox_GNSS_v3#37]
Has anyone tried this library with the new MIA-M10 chip? [https://www.u-blox.com/en/product/mia-m10-series](url)

**Comment by PaulZC** [comment]
Hi Simon (@simon88 ),

I think the answer is almost certainly "yes". Looking at the [Interface Reference](https://www.u-blox.com/sites/default/files/u-blox-M10-SPG-5.10_InterfaceDescription_UBX-21035062.pdf), it supports standard NMEA, UBX and (importantly) Configuration Interface messages. If it has any unique Configuration Interface Keys, we can easily add those.

Cheers,
Paul
